easy_admin:
    design:
        brand_color: 'rgba(180, 0, 0)'
        assets:
            favicon: '/assets/favicon.png'

    entities:
        User:
            class:  App\Entity\User
        Army:
            class:  App\Entity\Army
        Unit:
            class:  App\Entity\Unit
        Article:
            class:  App\Entity\Article

    site_name:  'WAR - Wargaming Army Builder'

    user:
        name_property_path: 'email'
        avatar_property_path: 'gravatar'