easy_admin:
    design:
        brand_color: 'rgba(180, 0, 0)'
        assets:
            favicon: '/assets/backend/favicon.png'

    entities:
        - App\Entity\User
        - App\Entity\UserArmy
        - App\Entity\UserArmyUnit
        - App\Entity\Article
        - App\Entity\Category
        - App\Entity\Army
        - App\Entity\Unit
        - App\Entity\UnitCategory
        - App\Entity\UnitCategoryHasUnitLimit
        - App\Entity\UnitLimit

    site_name:  'WAR - Wargaming Army Builder'

    user:
        name_property_path: 'email'
        avatar_property_path: 'gravatar'